"""Unified single-transcript judge (GPT + Claude)."""

from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Literal

from dotenv import load_dotenv
from langchain_anthropic import ChatAnthropic
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import END, START, StateGraph
from typing_extensions import NotRequired, TypedDict

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))
load_dotenv(_REPO_ROOT / ".env")

Provider = Literal["gpt", "claude"]

TRANSCRIPTS_DIR = _REPO_ROOT / "transcripts"
PROMPTS_DIR = _REPO_ROOT / "judge" / "prompts"
RUBRICS_DIR = _REPO_ROOT / "judge" / "rubrics"

DEFAULT_JUDGE_PROMPT = "judge_05"
DEFAULT_RUBRIC = "rubric_05"
DEFAULT_OPENAI_MODEL = "gpt-5.4"
DEFAULT_CLAUDE_MODEL = "claude-sonnet-4-6"
DEFAULT_REASONING = "medium"
MAX_ATTEMPTS = 3


class JudgeError(RuntimeError):
    """Raised when judging fails."""


@dataclass(slots=True)
class JudgeResult:
    """Final score summary and output location for a single judged transcript."""

    total_score: int
    max_score: int
    output_path: Path


class JudgeState(TypedDict):
    """LangGraph state for iterative model-call/validation repair attempts."""

    attempts: int
    system_prompt: str
    conversation_text: str
    num_turns: int
    last_output: NotRequired[str]
    last_error: NotRequired[str]
    grade_json: NotRequired[dict[str, Any]]


def _coerce_int(value: Any, default: int = 0) -> int:
    """Best-effort conversion to int with safe fallback to *default*."""

    if isinstance(value, bool):
        return int(value)
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(round(value))
    if isinstance(value, str):
        text = value.strip()
        if not text:
            return default
        try:
            return int(round(float(text)))
        except ValueError:
            return default
    return default


def _sanitize_text(value: Any) -> str:
    """Return a string representation, treating ``None`` as an empty string."""

    if value is None:
        return ""
    if isinstance(value, str):
        return value
    return str(value)


def _normalize_judge_explanations(payload: dict[str, Any]) -> dict[str, Any]:
    """Force explicit judge explanation fields, mirroring tutor normalization style."""

    out = dict(payload)
    overview = _sanitize_text(out.get("overview")).strip()
    reasoning = _sanitize_text(out.get("judge_reasoning")).strip()

    if not reasoning:
        if overview:
            reasoning = overview
        else:
            reasoning = (
                "Fallback reasoning generated by runtime: upstream response did not "
                "include explicit judge reasoning."
            )
    if not overview:
        overview = "No overview provided by model."

    out["overview"] = overview
    out["judge_reasoning"] = reasoning
    return out


def _env_truthy(name: str) -> bool:
    """True when the named env var is set to a common truthy token."""

    return os.environ.get(name, "").strip().lower() in {"1", "true", "yes", "on"}


def _require_openai_api_key() -> str:
    """Return OpenAI API key from env or raise ``JudgeError``."""

    key = os.environ.get("OPENAI_API_KEY") or os.environ.get("OPENAI_KEY")
    if not key:
        raise JudgeError("OPENAI_API_KEY environment variable is required but not set.")
    return key


def _require_anthropic_api_key() -> str:
    """Return Anthropic API key from env or raise ``JudgeError``."""

    key = os.environ.get("ANTHROPIC_API_KEY")
    if not key:
        raise JudgeError("ANTHROPIC_API_KEY environment variable is required but not set.")
    return key


def _extract_text_from_model_content(content: Any) -> str:
    """Normalize provider-specific model response content to plain text."""

    if isinstance(content, str):
        return content
    if isinstance(content, list):
        parts: list[str] = []
        for item in content:
            if isinstance(item, str):
                parts.append(item)
            elif isinstance(item, dict):
                text = item.get("text")
                if text is not None:
                    parts.append(_sanitize_text(text))
        return "\n".join(parts).strip()
    if isinstance(content, dict):
        if "text" in content:
            return _sanitize_text(content["text"])
    return _sanitize_text(content)


def _extract_json_object(text: str) -> str:
    """Extract the first JSON object from model output text."""

    # fenced code block first
    fenced = re.search(r"```(?:json)?\s*(\{.*\})\s*```", text, flags=re.DOTALL)
    if fenced:
        return fenced.group(1).strip()
    # Fallback to first balanced-brace span in raw text.
    start = text.find("{")
    if start == -1:
        raise JudgeError("No JSON object found in model output.")
    depth = 0
    for i in range(start, len(text)):
        ch = text[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    raise JudgeError("Unclosed JSON object in model output.")


def _parse_json_from_model_output(raw: str) -> dict[str, Any]:
    """Parse and validate model output as a top-level JSON object."""

    obj_text = _extract_json_object(raw)
    try:
        parsed = json.loads(obj_text)
    except json.JSONDecodeError as e:
        raise JudgeError(f"Invalid JSON from model: {e}") from e
    if not isinstance(parsed, dict):
        raise JudgeError(f"Expected JSON object, got {type(parsed).__name__}")
    return parsed


def _build_expected_schema(rubric_name: str) -> str:
    """Build the schema example injected into the judge prompt template.

    The schema is a concrete example that shows exactly what the output JSON must
    look like, including the dot-notation criterion keys (``"1.1"``, ``"1.2"`` …)
    and per-criterion maxes that match the rubric being used.

    Rubric max totals:
    - rubric_05 / rubric_06 : 46 pts  (1.1=8, 1.2=8, 1.3=8, 2.1=6, 2.2=6, 3.1=5, 3.2=5)
    - rubric_07             : 44 pts  (1.1=12, 1.2=6, 1.3=6, 2.1=4, 2.2=8, 3.1=4, 3.2=4)
    - rubric_08             : 40 pts  (1.1=12, 1.2=6, 1.3=2, 2.1=4, 2.2=8, 3.1=4, 3.2=4)
    - all others            : 47 pts  (default fallback, same shape as rubric_05)
    """

    _rn = rubric_name.strip().lower()

    if _rn == "rubric_08":
        # Section 1: 12+6+2=20, Section 2: 4+8=12, Section 3: 4+4=8  → total 40
        sample = {
            "sections": {
                "1_pedagogy": {
                    "criteria": {
                        "1.1": {
                            "deductions": [
                                {
                                    "sub_criterion_id": "1.1.A.a",
                                    "reason": "Example deduction reason.",
                                    "points": 12,
                                }
                            ],
                            "score": 0,
                            "max": 12,
                        },
                        "1.2": {"deductions": [], "score": 6, "max": 6},
                        "1.3": {
                            "deductions": [
                                {
                                    "sub_criterion_id": "1.3.A.a",
                                    "reason": "Example deduction reason.",
                                    "points": 2,
                                }
                            ],
                            "score": 0,
                            "max": 2,
                        },
                    },
                    "base": {"score": 6, "max": 20},
                },
                "2_dialogue_quality": {
                    "criteria": {
                        "2.1": {"deductions": [], "score": 4, "max": 4},
                        "2.2": {"deductions": [], "score": 8, "max": 8},
                    },
                    "base": {"score": 12, "max": 12},
                },
                "3_communication_quality": {
                    "criteria": {
                        "3.1": {"deductions": [], "score": 4, "max": 4},
                        "3.2": {"deductions": [], "score": 4, "max": 4},
                    },
                    "base": {"score": 8, "max": 8},
                },
            },
            "total_base_score": 26,
            "max_base_score": 40,
            "overview": "Concise rubric-based summary.",
            "judge_reasoning": "Explicit rationale for major deductions and score.",
            "total_score": 26,
            "max_score": 40,
            "judge_llm_calls": 1,
        }
    elif _rn == "rubric_07":
        # Section 1: 12+6+6=24, Section 2: 4+8=12, Section 3: 4+4=8  → total 44
        sample = {
            "sections": {
                "1_pedagogy": {
                    "criteria": {
                        "1.1": {
                            "deductions": [
                                {
                                    "sub_criterion_id": "1.1.A.a",
                                    "reason": "Example deduction reason.",
                                    "points": 12,
                                }
                            ],
                            "score": 0,
                            "max": 12,
                        },
                        "1.2": {"deductions": [], "score": 6, "max": 6},
                        "1.3": {
                            "deductions": [
                                {
                                    "sub_criterion_id": "1.3.A.a",
                                    "reason": "Example deduction reason.",
                                    "points": 2,
                                }
                            ],
                            "score": 4,
                            "max": 6,
                        },
                    },
                    "base": {"score": 10, "max": 24},
                },
                "2_dialogue_quality": {
                    "criteria": {
                        "2.1": {"deductions": [], "score": 4, "max": 4},
                        "2.2": {"deductions": [], "score": 8, "max": 8},
                    },
                    "base": {"score": 12, "max": 12},
                },
                "3_communication_quality": {
                    "criteria": {
                        "3.1": {"deductions": [], "score": 4, "max": 4},
                        "3.2": {"deductions": [], "score": 4, "max": 4},
                    },
                    "base": {"score": 8, "max": 8},
                },
            },
            "total_base_score": 30,
            "max_base_score": 44,
            "overview": "Concise rubric-based summary.",
            "judge_reasoning": "Explicit rationale for major deductions and score.",
            "total_score": 30,
            "max_score": 44,
            "judge_llm_calls": 1,
        }
    else:
        # rubric_05 / rubric_06 → 46 pts; unknown rubrics → 47 pts (safe default)
        max_score = 46 if _rn in {"rubric_05", "rubric_06"} else 47
        sample = {
            "sections": {
                "1_pedagogy": {
                    "criteria": {
                        "1.1": {
                            "deductions": [],
                            "score": 8,
                            "max": 8,
                        },
                        "1.2": {
                            "deductions": [],
                            "score": 8,
                            "max": 8,
                        },
                        "1.3": {
                            "deductions": [
                                {
                                    "sub_criterion_id": "1.3.A.a",
                                    "reason": "Example deduction reason.",
                                    "points": 2,
                                }
                            ],
                            "score": 6,
                            "max": 8,
                        },
                    },
                    "base": {"score": 22, "max": 24},
                },
                "2_dialogue_quality": {
                    "criteria": {
                        "2.1": {"deductions": [], "score": 6, "max": 6},
                        "2.2": {"deductions": [], "score": 4, "max": 6},
                    },
                    "base": {"score": 10, "max": 12},
                },
                "3_communication_quality": {
                    "criteria": {
                        "3.1": {"deductions": [], "score": 5, "max": 5},
                        "3.2": {"deductions": [], "score": 5, "max": 5},
                    },
                    "base": {"score": 10, "max": 10},
                },
            },
            "total_base_score": 42,
            "max_base_score": max_score,
            "overview": "Concise rubric-based summary.",
            "judge_reasoning": "Explicit rationale for major deductions and score.",
            "total_score": 42,
            "max_score": max_score,
            "judge_llm_calls": 1,
        }
    return json.dumps(sample, ensure_ascii=False, indent=2)


def load_judge_prompt(*, prompt_name: str = DEFAULT_JUDGE_PROMPT, rubric_name: str = DEFAULT_RUBRIC) -> str:
    """Load judge prompt template and inject rubric text plus JSON schema example."""

    prompt_path = PROMPTS_DIR / f"{prompt_name}.txt"
    rubric_path = RUBRICS_DIR / f"{rubric_name}.md"
    if not prompt_path.exists():
        raise JudgeError(f"Judge prompt not found: {prompt_path}")
    if not rubric_path.exists():
        raise JudgeError(f"Rubric not found: {rubric_path}")
    prompt_template = prompt_path.read_text(encoding="utf-8")
    rubric_text = rubric_path.read_text(encoding="utf-8")
    schema_text = _build_expected_schema(rubric_name.strip().lower())
    return prompt_template.replace("{rubric}", rubric_text).replace("{schema}", schema_text)


def _format_conversation_for_judge(transcript: dict[str, Any]) -> str:
    """Format transcript JSON into deterministic plain text for judge input."""

    lines: list[str] = []
    context = _sanitize_text(transcript.get("context")).strip()
    exercise = _sanitize_text(transcript.get("exercise")).strip()
    if context:
        lines.append("Context:")
        lines.append(context)
        lines.append("")
    if exercise:
        lines.append("Exercise:")
        lines.append(exercise)
        lines.append("")
    lines.append("Conversation:")
    exchanges = transcript.get("exchanges", [])
    if not isinstance(exchanges, list):
        return "\n".join(lines)
    for idx, ex in enumerate(exchanges, start=1):
        if not isinstance(ex, dict):
            continue
        student = _sanitize_text(ex.get("student")).strip()
        tutor = _sanitize_text(ex.get("tutor")).strip()
        lines.append(f"Turn {idx}")
        lines.append(f"Student: {student}")
        lines.append(f"Tutor: {tutor}")
    return "\n".join(lines)


_CRIT_ID_PAT = re.compile(r"^(\d+)[._](\d+)")


def _norm_cid(cid: str) -> str:
    """Normalize any criterion key to short ``X.Y`` dot-notation."""
    m = _CRIT_ID_PAT.match(str(cid))
    return f"{m.group(1)}.{m.group(2)}" if m else str(cid)


def _norm_criterion_value(val: dict[str, Any]) -> dict[str, Any]:
    """Normalize criterion value so score/max are direct keys (not nested under ``base``).

    Some model outputs wrap per-criterion scores under a ``"base"`` block:
    ``{"deductions": [], "base": {"score": 8, "max": 8}}``.

    The canonical form is direct keys:
    ``{"deductions": [], "score": 8, "max": 8}``.

    If direct ``score``/``max`` are already present they are kept unchanged.
    All other keys (e.g. ``deductions``) are preserved.
    """
    out = dict(val)
    if "score" not in out and "max" not in out:
        base = out.pop("base", None)
        if isinstance(base, dict):
            out["score"] = base.get("score", 0)
            out["max"] = base.get("max", 0)
    return out


def _normalize_criterion_keys(sections: dict[str, Any]) -> dict[str, Any]:
    """Normalize criterion structure inside each section before writing to disk.

    Handles all three observed model output shapes and converts them to the
    canonical nested-criteria form:
    ``section["criteria"]["1.1"] = {"score": N, "max": M, "deductions": [...]}``.

    Shape 1 – nested ``criteria`` dict (schema-compliant, most common for GPT):
    ``section["criteria"]["1_1_description"] = {"score": N, "max": M, ...}``

    Shape 2 – nested ``criteria`` dict with ``base``-wrapped scores:
    ``section["criteria"]["1.1"] = {"base": {"score": N, "max": M}, ...}``

    Shape 3 – flat criterion keys directly in the section dict:
    ``section["1.1"] = {"score": N, "max": M, ...}``
    ``section["1_1_description"] = {"base": {"score": N, "max": M}, ...}``

    In all cases, criterion IDs are also normalized to short ``X.Y`` dot-notation.
    Section-level keys like ``'1_pedagogy'`` and ``'base'`` are left intact.
    """
    out: dict[str, Any] = {}
    for sid, section in sections.items():
        if not isinstance(section, dict):
            out[sid] = section
            continue

        existing_criteria = section.get("criteria")
        if isinstance(existing_criteria, dict):
            normalized: dict[str, Any] = {}
            for cid, val in existing_criteria.items():
                dot_cid = _norm_cid(str(cid))
                normalized[dot_cid] = _norm_criterion_value(val) if isinstance(val, dict) else val
            out[sid] = {**section, "criteria": normalized}
            continue

        # Shape 3: criteria are flat keys directly in the section dict.
        flat_criteria: dict[str, Any] = {}
        non_criteria: dict[str, Any] = {}
        for k, v in section.items():
            m = _CRIT_ID_PAT.match(str(k))
            if m and isinstance(v, dict):
                dot_cid = f"{m.group(1)}.{m.group(2)}"
                flat_criteria[dot_cid] = _norm_criterion_value(v)
            else:
                non_criteria[k] = v

        if flat_criteria:
            out[sid] = {**non_criteria, "criteria": flat_criteria}
        else:
            out[sid] = section

    return out


def _sanitize_grade_payload(payload: dict[str, Any]) -> dict[str, Any]:
    """Coerce score fields to integers, normalize criterion keys, and ensure expected optional keys exist."""

    total_base = _coerce_int(payload.get("total_base_score"))
    max_base = _coerce_int(payload.get("max_base_score"), 46)
    total = _coerce_int(payload.get("total_score"), total_base)
    max_score = _coerce_int(payload.get("max_score"), max_base)
    out = dict(payload)
    out["total_base_score"] = total_base
    out["max_base_score"] = max_base
    out["total_score"] = total
    out["max_score"] = max_score
    out = _normalize_judge_explanations(out)
    out.setdefault("sections", {})
    sections = out.get("sections")
    if isinstance(sections, dict):
        out["sections"] = _normalize_criterion_keys(sections)
    return out


def _validate_grade_payload(payload: dict[str, Any]) -> dict[str, Any]:
    """Validate required score fields and numeric ranges in grade payload."""

    for key in ("total_base_score", "max_base_score", "total_score", "max_score"):
        if key not in payload:
            raise JudgeError(f"Missing required key: {key}")
        if not isinstance(payload[key], int):
            raise JudgeError(f"{key} must be integer, got {type(payload[key]).__name__}")
    if payload["total_score"] < 0 or payload["total_score"] > payload["max_score"]:
        raise JudgeError("total_score out of range")
    if payload["total_base_score"] < 0 or payload["total_base_score"] > payload["max_base_score"]:
        raise JudgeError("total_base_score out of range")
    return payload


def _order_grade_payload(payload: dict[str, Any]) -> dict[str, Any]:
    """Return payload with stable key ordering for readability and diffs."""

    ordered: dict[str, Any] = {}
    for key in (
        "sections",
        "total_base_score",
        "max_base_score",
        "overview",
        "judge_reasoning",
        "total_score",
        "max_score",
        "model",
        "judge_llm_calls",
        "timestamp_utc",
    ):
        if key in payload:
            ordered[key] = payload[key]
    for k, v in payload.items():
        if k not in ordered:
            ordered[k] = v
    return ordered


def _judge_repair_prompt(error: str) -> str:
    """Build repair instruction sent after a failed JSON validation pass."""

    return (
        "Your previous output was invalid.\n"
        f"Validation error: {error}\n"
        "Return ONLY valid JSON object, no markdown.\n"
        "Required integer keys: total_score, max_score, total_base_score, max_base_score."
    )


def _create_model_invoke(provider: Provider, model_name: str, api_key: str, reasoning: str) -> Callable[[list[Any]], Any]:
    """Create a provider-specific callable used to invoke the judge model."""

    if provider == "gpt":
        kwargs: dict[str, Any] = {"model": model_name, "temperature": 0, "api_key": api_key}
        if reasoning in {"low", "medium", "high"}:
            kwargs["reasoning"] = {"effort": reasoning}
        model = ChatOpenAI(**kwargs)
        return model.invoke
    model = ChatAnthropic(model=model_name, temperature=0, api_key=api_key)
    return model.invoke


def _create_judge_graph(*, invoke_model: Callable[[list[Any]], Any]) -> Any:
    """Build a retrying LangGraph pipeline for judge generation and validation."""

    def judge_node(state: JudgeState) -> dict[str, Any]:
        """Call the model with either a fresh prompt or repair prompt."""

        messages = [SystemMessage(content=state["system_prompt"])]
        if state.get("last_error") and state.get("last_output"):
            messages.append(
                HumanMessage(
                    content=_judge_repair_prompt(_sanitize_text(state["last_error"]))
                    + "\n\nPrevious JSON:\n"
                    + _sanitize_text(state["last_output"])
                )
            )
        messages.append(HumanMessage(content=state["conversation_text"]))
        resp = invoke_model(messages)
        return {
            "last_output": _extract_text_from_model_content(getattr(resp, "content", resp)),
            "attempts": int(state.get("attempts", 0)) + 1,
        }

    def validate_node(state: JudgeState) -> dict[str, Any]:
        """Parse, sanitize, and validate model JSON output."""

        try:
            parsed = _parse_json_from_model_output(_sanitize_text(state.get("last_output", "")))
            sanitized = _sanitize_grade_payload(parsed)
            validated = _validate_grade_payload(sanitized)
            return {"grade_json": _order_grade_payload(validated), "last_error": None}
        except JudgeError as e:
            return {"grade_json": None, "last_error": str(e)}

    def route(state: JudgeState) -> str:
        """Route to end on success/max attempts, otherwise request another retry."""

        if state.get("grade_json") is not None:
            return END
        return END if int(state.get("attempts", 0)) >= MAX_ATTEMPTS else "judge"

    graph = StateGraph(JudgeState)
    graph.add_node("judge", judge_node)
    graph.add_node("validate", validate_node)
    graph.add_edge(START, "judge")
    graph.add_edge("judge", "validate")
    graph.add_conditional_edges("validate", route, {"judge": "judge", END: END})
    return graph.compile()


def _judge_transcript(
    transcript_name: str,
    *,
    provider: Provider,
    prompt_name: str,
    rubric_name: str,
    output_name: str | None,
) -> JudgeResult:
    """Run the complete judging flow for one transcript and write output JSON."""

    transcript_path = TRANSCRIPTS_DIR / f"{transcript_name}.json"
    if not transcript_path.exists():
        raise JudgeError(f"Transcript not found: {transcript_path}")
    try:
        transcript = json.loads(transcript_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        raise JudgeError(f"Invalid transcript JSON: {transcript_path}: {e}") from e
    if not isinstance(transcript, dict):
        raise JudgeError("Transcript JSON must be an object.")
    exchanges = transcript.get("exchanges")
    if not isinstance(exchanges, list) or not exchanges:
        raise JudgeError("Transcript must contain non-empty 'exchanges' list.")

    if provider == "gpt":
        model_name = os.environ.get("OPENAI_MODEL", DEFAULT_OPENAI_MODEL)
        api_key = _require_openai_api_key()
        reasoning = os.environ.get("JUDGE_OPENAI_REASONING_EFFORT", DEFAULT_REASONING).strip().lower() or DEFAULT_REASONING
    else:
        model_name = os.environ.get("ANTHROPIC_MODEL", DEFAULT_CLAUDE_MODEL)
        api_key = _require_anthropic_api_key()
        reasoning = "off"

    invoke_model = _create_model_invoke(provider, model_name, api_key, reasoning)
    graph = _create_judge_graph(invoke_model=invoke_model)

    system_prompt = load_judge_prompt(prompt_name=prompt_name, rubric_name=rubric_name)
    conversation_text = _format_conversation_for_judge(transcript)
    result = graph.invoke(
        {
            "attempts": 0,
            "system_prompt": system_prompt,
            "conversation_text": conversation_text,
            "num_turns": len(exchanges),
        }
    )
    grade_json = result.get("grade_json")
    if grade_json is None:
        raise JudgeError(f"Judge failed to produce valid grade JSON. Last error: {result.get('last_error')}")

    grade_payload = dict(grade_json)
    if provider == "gpt":
        grade_payload["model"] = {
            "provider": "openai",
            "model": model_name,
            "temperature": 0,
            "reasoning_effort": reasoning,
        }
    else:
        grade_payload["model"] = {"provider": "anthropic", "model": model_name, "temperature": 0}
    grade_payload["judge_llm_calls"] = int(result.get("attempts", 0))
    if _env_truthy("JUDGE_INCLUDE_TIMESTAMP"):
        grade_payload["timestamp_utc"] = datetime.now(timezone.utc).isoformat()
    grade_payload = _order_grade_payload(grade_payload)

    out_doc = dict(transcript)
    out_doc.pop("grade", None)
    out_doc["grade"] = grade_payload
    if output_name is None:
        out_name = transcript_path.name
    else:
        out_name = f"{output_name}.json"
    output_path = transcript_path.with_name(out_name)
    output_path.write_text(json.dumps(out_doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return JudgeResult(
        total_score=int(grade_payload["total_score"]),
        max_score=int(grade_payload["max_score"]),
        output_path=output_path,
    )


def judge_transcript_gpt(
    transcript_name: str,
    *,
    prompt_name: str = DEFAULT_JUDGE_PROMPT,
    rubric_name: str = DEFAULT_RUBRIC,
    output_name: str | None = None,
) -> JudgeResult:
    """Judge a single transcript using OpenAI GPT provider settings."""

    return _judge_transcript(
        transcript_name,
        provider="gpt",
        prompt_name=prompt_name,
        rubric_name=rubric_name,
        output_name=output_name,
    )


def judge_transcript_claude(
    transcript_name: str,
    *,
    prompt_name: str = DEFAULT_JUDGE_PROMPT,
    rubric_name: str = DEFAULT_RUBRIC,
    output_name: str | None = None,
) -> JudgeResult:
    """Judge a single transcript using Anthropic Claude provider settings."""

    return _judge_transcript(
        transcript_name,
        provider="claude",
        prompt_name=prompt_name,
        rubric_name=rubric_name,
        output_name=output_name,
    )


def judge_transcript(
    transcript_name: str,
    *,
    provider: Provider = "gpt",
    prompt_name: str = DEFAULT_JUDGE_PROMPT,
    rubric_name: str = DEFAULT_RUBRIC,
    output_name: str | None = None,
) -> JudgeResult:
    """Provider-agnostic entrypoint to judge a single transcript."""

    return _judge_transcript(
        transcript_name,
        provider=provider,
        prompt_name=prompt_name,
        rubric_name=rubric_name,
        output_name=output_name,
    )


__all__ = [
    "JudgeError",
    "JudgeResult",
    "load_judge_prompt",
    "judge_transcript",
    "judge_transcript_gpt",
    "judge_transcript_claude",
]


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Judge one transcript with GPT or Claude.")
    parser.add_argument("transcript_name", help="Transcript stem relative to transcripts/ (no .json)")
    parser.add_argument("--provider", choices=["gpt", "claude"], default="gpt")
    parser.add_argument("--prompt", default=DEFAULT_JUDGE_PROMPT)
    parser.add_argument("--rubric", default=DEFAULT_RUBRIC)
    args = parser.parse_args()
    result = judge_transcript(
        args.transcript_name,
        provider=args.provider,  # type: ignore[arg-type]
        prompt_name=args.prompt,
        rubric_name=args.rubric,
    )
    print(f"Judged {args.transcript_name}: {result.total_score}/{result.max_score}")
    print(f"Output: {result.output_path}")

